### PR TITLE
Update Buildscript and apply Spotless

### PR DESCRIPTION
**Pull request by Shibva**
Note: Additonal Matemence is required; an unresolved java.lang.IllegalArgumentException has been noticed and needs to be fixed.

Dependencies might need to be updated and in turn could resolve the error

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Shibva fix your pr because it not pass the check

**Comment by Shibva** [comment]
i thought the changes were too many, maybe someone else shoud try it, closing

**Comment by Dream-Master** [comment]
@Shibva I don’t get it why you close a pr when some problems occurred ? Just fix.

**Comment by Shibva** [comment]
im not equipt to handle extensive changes, im still just a beginer in all of this; futhermore I did make a note that there were some issues wtih the java.lang.illegalArgumentException i

it would be better if someone more experienced were to update it instead of me. being completely honest here

**Pull request closed without merging**
