### PR TITLE
Implement transvector interface chaining(redirection)

### PR DESCRIPTION
**Pull request by LewisSaber**
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11163
Demo:
https://youtu.be/YyILcM8HUbQ
So what it does is:
When you connect Transvector A to transvector B, Transvector A will be connected to block that Transvector B is connected to,
This feature doesnt have a lot of uses, but can be handy when original block is blocked

### CODE REVIEW

**Comment by boubou19** [comment]
The limitation of 4 blocks is done for a reason. If you need more sides to interact with a machine, just build another one.

**Comment by LewisSaber** [comment]
> The limitation of 4 blocks is done for a reason. If you need more sides to interact with a machine, just build another one.

it doesnt increase range tho

**Comment by boubou19** [comment]
Yeah but for each transvector, you can add 5 mores on them. And it's 100% sure people will abuse this to stupid extents, then they'll complain because game broke.

**Comment by boubou19** [comment]
After some clarification with Lewis, it just allows for a transvector to be bound to another transvector, within the initial 4 block range with the target block. Makes no sense to bind a transvector to another one with 4 block range of the target block, while you can just bind it to the target block instead

**Pull request closed without merging**
